appium_config:
  #配置appium启动参数
  appium_start_cmd: "appium"
  remote_URL: "http://127.0.0.1:4723/wd/hub"
  platformName: "Android"
  deviceName: "e362ce5e"
  platformVersion: "8.0"
  appPackage: "com.ugreen.iot"
  appActivity: "com.ugreen.iot/com.guoxuansource.MainActivity"
  unicodeKeyboard: True
  resetKeyboard: True

